[package]
name = "metacat"
version = "0.1.0"
edition = "2021"

[dependencies]
google-drive3 = "4.0.4+20220225"
poise = "0.5.2"
tokio = { version = "1.4.0", features = ["rt","macros","rt-multi-thread"] }
